/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ControlInterfaz;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class IngresoAlmacen extends javax.swing.JFrame implements InterfazVista {

    /**
     * Creates new form Ingreso_Almacen
     */
    private ArrayList <String> nombp;
    private ArrayList <String> nombm;
    public IngresoAlmacen(ArrayList <String> a,ArrayList <String> b) {
//        proveedor.removeAllItems();
  //      producto.removeAllItems();
        nombp =a;
        nombm=b;
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptarIngreso = new javax.swing.JButton();
        cancelarIngreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        proveedor = new javax.swing.JComboBox<>();
        producto = new javax.swing.JComboBox<>();
        jCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aceptarIngreso.setText("Aceptar");

        cancelarIngreso.setText("Cancelar");

        jLabel1.setText("Proveedor");

        jLabel2.setText("Producto");

        jLabel3.setText("Cantidad Ingresada");

        proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });

        producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(aceptarIngreso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(proveedor, 0, 107, Short.MAX_VALUE)
                    .addComponent(cancelarIngreso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarIngreso)
                    .addComponent(cancelarIngreso))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorActionPerformed

    private void jCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCantidadActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarIngreso;
    private javax.swing.JButton cancelarIngreso;
    private javax.swing.JTextField jCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> producto;
    private javax.swing.JComboBox<String> proveedor;
    // End of variables declaration//GEN-END:variables
   
    
    @Override
    public void setControlador(ControlInterfaz c) {
        aceptarIngreso.addActionListener(c);
        cancelarIngreso.addActionListener(c);   
    }

    @Override
    public void init() {
        initComponents();
        proveedor.removeAllItems();
        producto.removeAllItems();

        llenarComboProveedor(nombp);
        llenarComboMaterial (nombm);
        setVisible(true);
        setLocationRelativeTo(null);
        aceptarIngreso.setActionCommand(ACEPTAINGRESO);
        cancelarIngreso.setActionCommand(CANCELAINGRESO);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public void llenarComboProveedor(ArrayList <String> a){
        for(int i=0; i<a.size();i++){
            proveedor.addItem(a.get(i));
        }
    }
    public void llenarComboMaterial(ArrayList <String> a){
        for(int i=0; i<a.size();i++){
            producto.addItem(a.get(i));
        }
    }
    public void cerrar(){
        setVisible(false);
    }

        public String getProducto(){
        String prod=(String)producto.getSelectedItem();
        System.out.print(prod);
        return prod;
    }
    public String getProveedor(){
        String prov=(String)proveedor.getSelectedItem();
        System.out.print(prov);
        return prov;
    }
    public int getCantidad(){
        return Integer.parseInt(jCantidad.getText().trim());
    }
}
